@startuml
title Homework Use Case

:User: as user
(Run com.demo.App) as (use)
user --> (use)

note right of (use)
Has two configuration files.
- homework-default.properties (default values)
    file-input-scanner.filename=sample-users.txt
    file-output-repository.filename=output.txt
    bruteforce-permutation-dictionary.min-len=1
    bruteforce-permutation-dictionary.max-len=2
    bruteforce-permutation-dictionary.allowed-characters=abc
    english-dictionary.filename=sample-english-dictionary.txt
    thread-pool.size=1
- %TEMP%/homework.properties (overriding defaults)
end note
@enduml